### ISSUE TITLE
关于样式文件的引入

### ISSUE THREAD

**Issue by baojingma** [ggpp224/chanapp#1]
我刚才根据mutants的文档，创建了一个项目，发现demo项目的样式都是写在style里面的，而webpackconfig里面还写了关于postcss的配置，但又没有main.less的引用，感觉很奇怪，到底是推荐在style上写样式呢，还是用样式文件

**Comment by ggpp224** [comment]
已提供less引入的示例: src/www/css/main.less 和src/components/pages/Home/page.less.

version >= 0.3.1

boilerpate 项目简单展示了inline-style 和 css文件的使用方式， 用户可以根据习惯和爱好自行选取， 两种方式都可， 不作推荐。

但是如果要使用chanjet-ui中组件， 组件api中style只接收 inline-style, 其它的可以自由选取或混合使用。
